application/models.py
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):

    __tablename__ = 'login-users'

    id = db.Column(
        db.Integer,
        primary_key = True
    )
    name = db.Column(
        db.String(60),
        unique=True,
        nullable=True
    )
    email = db.Column(
        db.String(60),
        unique=True,
        nullable=True
    )
    password = db.Column(
        db.String(200),
        primary_key=False,
        unique=False,
        nullable=False
    )
    created = db.Column(
        db.DateTime,
        index=False,
        unique=False,
        nullable=True
    )
    last_login = db.Column(
        db.DateTime,
        index=False,
        unique=False,
        nullable=True
    )

    def set_password(self, password):
        self.password = generate_password_hash(
            password,
            method='sha256'
        )

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return self.name

application/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Optional

class SignupForm(FlaskForm):

    name = StringField(
        'Name',
        [DataRequired()]
    )

    email = StringField(
        'Email',
        [
            Email(message=('Not a valid email address')),
            DataRequired()
        ]
    )
    password = PasswordField(
        'Password',
        validators=[
            DataRequired(),
            Length(min=6,message='Select a stronger password')
        ]
    )
    confirm = PasswordField(
        'Confirm your password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match')
        ]
    )
    submit = SubmitField('Register')

class LoginForm(FlaskForm):

    email = StringField(
        'Email',
        [
            Email(message=('Not a valid email address')),
            DataRequired()
        ]
    )
    password = PasswordField(
        'Password',
        validators=[
            DataRequired(),
            Length(min=6,message='Select a stronger password')
        ]
    )

    submit = SubmitField('Log in')

application/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()

def create_app():
    app = Flask(
        __name__, 
        instance_relative_config=False # looks for config.py in basedir (where create_app is called)
    )

    app.config.from_object('config.Config')

    db.init_app(app)
    login_manager.init_app(app)

    with app.app_context():
        from . import routes
        from . import auth

        app.register_blueprint(routes.main_bp)
        app.register_blueprint(auth.auth_bp)
        
        db.create_all()

        return app

application/auth.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import login_user, current_user
from .forms import SignupForm, LoginForm
from .models import db, User
from . import login_manager

auth_bp = Blueprint(
    'auth_bp', 
    __name__, 
    template_folder='templates',
    static_folder='static'
)

@auth_bp.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            print(next_page)
            return redirect(next_page or url_for('main_bp.dashboard'))
        return render_template('login.html',form=form,invalid_credentials=True)
    return render_template('login.html',form=form,invalid_credentials=False)

@auth_bp.route('/signup', methods=['GET','POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(
                name = form.name.data,
                email = form.email.data,
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            login_user(user)
            return redirect(url_for('main_bp.dashboard'))
        return render_template('signup.html',form=form,user_exists=True)
    return render_template('signup.html',form=form,user_exists=False)

@login_manager.user_loader
def load_user(user_id):
    if user_id is not None:
        return User.query.get(user_id)
    return None

@login_manager.unauthorized_handler
def unauthorized():
    print('You must be logged in to view that page')
    return redirect(url_for('auth_bp.login'))

application/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required, logout_user
from .models import db, User

main_bp = Blueprint(
    'main_bp',
    __name__, 
    template_folder='templates',
    static_folder='static'
)

@main_bp.route('/',methods=['GET'])
@login_required
def dashboard():
    return render_template('home.html',current_user=current_user)

@main_bp.route('/users',methods=['GET'])
@login_required
def users():
    users = User.query.all()
    return render_template('users.html',current_user=current_user,users=users)

@main_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_bp.login'))

application/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center mb-5 mt-5">
            Welcome back {{ current_user }}
        </h2>
        <div class="text-center">
            <a href="/logout" class="btn btn-large btn-primary">Logout</a>
        </div>        
    </div>
{% endblock content %}

application/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Contact us</title>
        <meta charset="utf-8">
        <meta name="description" content={{description}}>
        <link rel="shortcut icon" href="/favicon.ico">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
        {% block content %}
            
        {% endblock content %}
    </body>
</html>

application/templates/login.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-2">
                <h2 class="text-center mt-5 mb-5">Login</h2>
                <form method="POST">
                    {{ form.csrf_token }}
                    <div class="form-group row">
                        <div class="col-md-4">
                            {{ form.email.label }}
                        </div>
                        <div class="col-md-8">
                            {{ form.email(class="form-control") }}
                        </div>
                        {% if form.email.errors %}
                            <ul>
                                {% for error in form.email.errors %}
                                    <li>
                                        <small class="text-danger">
                                            {{ error }}
                                        </small>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            {{ form.password.label }}
                        </div>
                        <div class="col-md-8">
                            {{ form.password(class="form-control") }}
                        </div>
                        {% if form.email.errors %}
                            <ul>
                                {% for error in form.email.errors %}
                                    <li>
                                        <small class="text-danger">
                                            {{ error }}
                                        </small>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    
                    {{ form.submit(class="btn btn-primary btn-block") }}
                    {% if invalid_credentials %}
                        <small class="text-danger">
                            Invalid email/password combination.
                        </small>
                    {% endif %}
                    <div class="text-center mt-2">
                        Don't have an account? <a href="{{ url_for('auth_bp.signup') }}">Sign up. </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

application/templates/signup.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-2">
                <h2 class="text-center mt-5 mb-5">Register</h2>
                <form method="POST">
                    {{ form.csrf_token }}
                    <div class="form-group row">
                        <div class="col-md-4">
                            {{ form.name.label }}
                        </div>
                        <div class="col-md-8">
                            {{ form.name(class="form-control") }}
                            {% if form.name.errors %}
                                {% for error in form.name.errors %}
                                    <small class="text-danger">
                                        {{ error }} <br>
                                    </small>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            {{ form.email.label }}
                        </div>
                        <div class="col-md-8">
                            {{ form.email(class="form-control") }}
                            {% if form.email.errors %}
                                {% for error in form.email.errors %}
                                    <small class="text-danger">
                                        {{ error }} <br>
                                    </small>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            {{ form.password.label }}
                        </div>
                        <div class="col-md-8">
                            {{ form.password(class="form-control") }}
                            {% if form.password.errors %}
                                {% for error in form.password.errors %}
                                    <small class="text-danger">
                                        {{ error }} <br>
                                    </small>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4">
                            {{ form.confirm.label }}
                        </div>
                        <div class="col-md-8">
                            {{ form.confirm(class="form-control") }}
                            {% if form.confirm.errors %}
                                {% for error in form.confirm.errors %}
                                    <small class="text-danger">
                                        {{ error }} <br>
                                    </small>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    {{ form.submit(class="btn btn-primary btn-block") }}
                    {% if user_exists %}
                        <small class="text-danger">
                            A user already exists with that email address.
                        </small>
                    {% endif %}
                    <div class="text-center mt-2">
                        Already have an account? <a href="{{ url_for('auth_bp.login') }}">Log in. </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

application/templates/users.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center mt-5">
            Hi {{ current_user.name }}! Your details below
        </h2>
        <ul>
            <li>Email: {{ current_user.email }}</li>
        </ul>
        <div class="text-center">
            <a href="/logout" class="btn btn-large btn-primary">Logout</a>
        </div>
        
        <h4 class="text-center mb-5 mt-5">
            All users
        </h4>
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.name }}</td>
                        <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}